# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9212fa9e7825fe90a68715e8b0eb3f5214142abf6d3474023934c27bd3fa6a8d53ccfbe291664e0f390d99523a2d2d13f002d08b256e774f0aa11e0546d389c0

test:
  secret_key_base: 41fa20036756e036565bae81f424a190636b471738f12f289331e9058305904ebb5f7d34395a393a5afe625f4ddfce50a6f4ff8b5a413136403a42ced9ef298b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
